### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.tpu' has no attribute 'InputPipelineConfig'

### ISSUE THREAD

**Issue by zhuoran918** [ProHiryu/albert-chinese-ner#18]
hello,在自己运行的时候出现
Traceback (most recent call last):
  File "albert_ner.py", line 845, in <module>
    tf.app.run()
  File "C:\Users\pangpang\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "albert_ner.py", line 671, in main
    is_per_host = tf.contrib.tpu.InputPipelineConfig.PER_HOST_V2
AttributeError: module 'tensorflow.contrib.tpu' has no attribute 'InputPipelineConfig'这个问题，我的tensorflow版本是1.8.0，是tensorflow版本的问题所以才报错的吗？

**Comment by ProHiryu** [comment]
是的，最好使用1.15试一下
