### ISSUE TITLE
修改了get_labels，也修改了tag的个数，报错

### ISSUE THREAD

**Issue by kFoodie** [ProHiryu/albert-chinese-ner#24]
W0428 10:19:42.609030 140066161387328 deprecation.py:323] From /data/glusterfs_sharing_04_v2/11117720/albert-chinese-ner-master/tf_metrics.py:142: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
ERROR:tensorflow:Error recorded from evaluation_loop: index 7 is out of bounds for axis 0 with size 7
E0428 10:19:42.708933 140066161387328 error_handling.py:75] Error recorded from evaluation_loop: index 7 is out of bounds for axis 0 with size 7
INFO:tensorflow:evaluation_loop marked as finished
I0428 10:19:42.709069 140066161387328 error_handling.py:101] evaluation_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0428 10:19:42.709154 140066161387328 error_handling.py:135] Reraising captured error
Traceback (most recent call last):
  File "albert_ner.py", line 847, in <module>
    tf.app.run()
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "albert_ner.py", line 787, in main
    result = estimator.evaluate(input_fn=eval_input_fn, steps=eval_steps, checkpoint_path=filename)
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3056, in evaluate
    rendezvous.raise_errors()
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3051, in evaluate
    name=name)
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 480, in evaluate
    name=name)
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 522, in _actual_eval
    return _evaluate()
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 504, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1511, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1547, in _call_model_fn_eval
    features, labels, ModeKeys.EVAL, config)
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2857, in _call_model_fn
    config)
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3126, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1663, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2005, in _call_model_fn
    return estimator_spec.as_estimator_spec()
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 379, in as_estimator_spec
    host_call_ret = _OutfeedHostCall.create_cpu_hostcall(host_calls)
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2076, in create_cpu_hostcall
    ret[name] = host_fn(*tensors)
  File "albert_ner.py", line 531, in metric_fn
    precision = tf_metrics.precision(label_ids, predictions, 7, [2, 3, 4, 5, 6, 7], average="macro")
  File "/data/glusterfs_sharing_04_v2/11117720/albert-chinese-ner-master/tf_metrics.py", line 47, in precision
    cm, pos_indices, average=average)
  File "/data/glusterfs_sharing_04_v2/11117720/albert-chinese-ner-master/tf_metrics.py", line 196, in metrics_from_confusion_matrix
    cm_mask[idx, :] = 1
IndexError: index 7 is out of bounds for axis 0 with size 7

**Comment by kFoodie** [comment]
precision = tf_metrics.precision(label_ids, predictions, 7, [2, 3, 4, 5, 6, 7], average="macro")
这里的‘7’，我改成了0，还是报错。。这是为啥。。

**Comment by kFoodie** [comment]
找到原因了，是那个[2,3,4,5,6,7]报的错。
pos_indices : list of int, optional
        The indices of the positive classes
positive classes指的是有标注的吗？比如说BI0X？

**Comment by kFoodie** [comment]
感觉应该是BI吧，OX应该不算。。
